apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: team3
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 1m

    rule_files:
      - "/etc/prometheus/prometheus-alert-rules.yaml"

    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: "5000"
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
