apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: team3
data:
  prometheus-alert-rules.yaml: |
    groups:
    - name: example
      rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 1 minute."
