apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library-inventory-pvc
  namespace: team3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "" # Ensure this is set to match the PV's StorageClass or left empty for direct binding
