apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-alertmanager
  namespace: team3
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-077d9d0200def4885
    fsType: ext4
