apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: library-inventory-replicaset
  namespace: team3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: library-inventory
  template:
    metadata:
      labels:
        app: library-inventory
    spec:
      containers:
        - name: library-inventory
          image: orange18036/team3-library
          ports:
            - containerPort: 5000
