apiVersion: v1
kind: Service
metadata:
  name: library-inventory-service
  namespace: omar
spec:
  type: NodePort  
  ports:
    - port: 5000      
      targetPort: 5000 
      nodePort: 30000  
  selector:
    app: library-inventory 
