apiVersion: v1
kind: Service
metadata:
  name: library-inventory-service
  namespace: team3
spec:
  type: LoadBalancer # Changed from NodePort to LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: library-inventory
