apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: team3
spec:
  type: LoadBalancer
  ports:
    - port: 80 # Change the external port to 80
      targetPort: 3000 # Keep the target port as 3000 (Grafana's default port)
  selector:
    app: grafana
